export const STATUS = {
    COMPLETE: 'COMPLETE',
    IN_PROGRESS: 'IN_PROGRESS',
    NOT_STARTED: 'NOT_STARTED'
};

export const QUESTION_TYPE = {
    TEXT: 'TEXT',
    CHOICE: 'CHOICE',
    NUMBER: 'NUMBER',
    GROUPED_CHOICE: 'GROUPED_CHOICE',
    FILE: 'FILE',
};