export const STATUS = {
    COMPLETE: 'COMPLETE',
    IN_PROGRESS: 'IN_PROGRESS',
    NOT_STARTED: 'NOT_STARTED'
};

export const QUESTION_TYPE = {
    TEXT: 'TEXT',
    CHOICE: 'CHOICE',
    MULTIPLE_CHOICE: 'MULTIPLE_CHOICE',
    NUMBER: 'NUMBER',
    GROUPED: 'GROUPED',
    FILE: 'FILE',
    SELECT: 'SELECT',
};